name: liquid-os
description: My personal OS image.
base-image: ghcr.io/ublue-os/aurora-dx-nvidia-open
image-version: stable

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: dnf
    repos:
      cleanup: true
      nonfree: negativo17
      copr:
        - atim/starship
      files:
        - https://negativo17.org/repos/fedora-steam.repo
    install:
      skip-unavailable: true
      packages:
        - starship
        - steam

  - type: script
    snippets:
      - |
        # set -e forza il fallimento se un comando non va a buon fine
        set -e
        echo "--- SCARICO CURSOR ---"
        
        # Usiamo l'API ufficiale con headers completi per evitare blocchi
        curl -L -f -A "Mozilla/5.0" -o /usr/bin/cursor.appimage "https://cursor.com/api/download?platform=linux&format=appimage"

        # Controllo di sicurezza: se il file è più piccolo di 100MB, qualcosa è andato storto
        FILESIZE=$(stat -c%s "/usr/bin/cursor.appimage")
        if [ $FILESIZE -lt 100000000 ]; then
            echo "ERRORE: Il file scaricato è troppo piccolo ($FILESIZE byte). Download corrotto."
            exit 1
        fi

        chmod +x /usr/bin/cursor.appimage
        
        echo "--- CREO WRAPPER ---"
        cat <<'EOF' > /usr/bin/cursor
        #!/bin/bash
        exec /usr/bin/cursor.appimage --no-sandbox "$@"
        EOF
        chmod +x /usr/bin/cursor
        
        echo "--- CREO DESKTOP FILE ---"
        mkdir -p /usr/share/applications
        cat <<EOF > /usr/share/applications/cursor.desktop
        [Desktop Entry]
        Name=Cursor
        Exec=/usr/bin/cursor %U
        Terminal=false
        Type=Application
        Icon=code
        Categories=Development;TextEditor;
        EOF

        echo "--- VERIFICA FINALE ---"
        ls -lh /usr/bin/cursor*
        

      - |
        echo "--- CONFIGURO FLATPAK ---"
        mkdir -p /usr/share/ublue-os
        cat <<EOF > /usr/share/ublue-os/default-flatpaks.json
        {
          "system": {
            "install": [
              "org.gnome.Loupe",
              "org.telegram.desktop",
              "org.videolan.VLC",
              "org.kde.krita",
              "org.darktable.Darktable",
              "org.blender.Blender",
              "org.onlyoffice.desktopeditors",
              "com.transmissionbt.Transmission",
              "org.jellyfin.JellyfinServer",
              "org.kde.kdenlive",
              "fr.handbrake.ghb"
            ]
          }
        }
        EOF

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          - org.gnome.Loupe
          - org.telegram.desktop
          - org.videolan.VLC
          - org.kde.krita
          - org.darktable.Darktable
          - org.blender.Blender
          - org.onlyoffice.desktopeditors
          - com.transmissionbt.Transmission
          - org.jellyfin.JellyfinServer
          - org.kde.kdenlive
          - fr.handbrake.ghb

  - type: signing
